# version: '3.8'

# services:
#   postgres:
#     image: postgres:16
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: medicalapp
#     ports:
#       - '5432:5432'
#     volumes:
#       - /home/postgres/postgres_data:/var/lib/postgresql/data # Make sure this directory exists
#     networks:
#       - app-network
#     restart: unless-stopped # Ensures container restarts if it crashes or the server reboots

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: medicalapp
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: medicalapp
#     depends_on:
#       - postgres
#     networks:
#       - app-network
#     ports:
#       - '3000:3000'
#     command: ['npm', 'run', 'start:dev']
#     restart: unless-stopped # Ensures container restarts if it crashes or the server reboots

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   postgres-data:
#     driver: local

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicalapp
    environment:
      POSTGRES_HOST: ep-bitter-breeze-ad3muiqv-pooler.c-2.us-east-1.aws.neon.tech # Neon DB host
      POSTGRES_PORT: 5432
      POSTGRES_USER: neondb_owner # Neon DB user
      POSTGRES_PASSWORD: npg_G3MNxOh6YijT # Neon DB password
      POSTGRES_DB: neondb # Neon DB name
      SSL_MODE: require
      CHANNEL_BINDING: require
    networks:
      - app-network
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start:dev']
    restart: unless-stopped # Ensures container restarts if it crashes or the server reboots

networks:
  app-network:
    driver: bridge
