server {
    listen 80;
    server_name api.care-bd.xyz care-bd.xyz www.care-bd.xyz;

    # Certbot challenge location
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
