export const medicalInstitutes = [
  // Public Medical Colleges
  { instituteName: 'Public Medical college', type: 'Public' },
  { instituteName: 'Dhaka Medical College', type: 'Public' },
  { instituteName: 'Sir Salimullah Medical College', type: 'Public' },
  { instituteName: 'Shaheed Suhrawardy Medical College', type: 'Public' },
  { instituteName: 'Mymensingh Medical College', type: 'Public' },
  { instituteName: 'Chittagong Medical College', type: 'Public' },
  { instituteName: 'Rajshahi Medical College', type: 'Public' },
  { instituteName: 'MAG Osmani Medical College', type: 'Public' },
  { instituteName: 'Sher-e-Bangla Medical College', type: 'Public' },
  { instituteName: 'Rangpur Medical College', type: 'Public' },
  { instituteName: 'Cumilla Medical College', type: 'Public' },
  { instituteName: 'Khulna Medical College', type: 'Public' },
  { instituteName: 'Shaheed Ziaur Rahman Medical College', type: 'Public' },
  { instituteName: 'Faridpur Medical College', type: 'Public' },
  { instituteName: 'Dinajpur Medical College', type: 'Public' },
  { instituteName: 'Pabna Medical College', type: 'Public' },
  { instituteName: 'Noakhali Medical College', type: 'Public' },
  { instituteName: "Cox's Bazar Medical College", type: 'Public' },
  { instituteName: 'Jashore Medical College', type: 'Public' },
  { instituteName: 'Satkhira Medical College', type: 'Public' },
  { instituteName: 'Shahid Syed Nazrul Islam Medical College', type: 'Public' },
  { instituteName: 'Kushtia Medical College', type: 'Public' },
  { instituteName: 'Gopalganj Medical College', type: 'Public' },
  { instituteName: 'Shaheed Tajuddin Ahmad Medical College', type: 'Public' },
  { instituteName: 'Tangail Medical College', type: 'Public' },
  { instituteName: 'Jamalpur Medical College', type: 'Public' },
  { instituteName: 'Manikganj Medical College', type: 'Public' },
  { instituteName: 'Shaheed M. Monsur Ali Medical College', type: 'Public' },
  { instituteName: 'Patuakhali Medical College', type: 'Public' },
  { instituteName: 'Rangamati Medical College', type: 'Public' },
  { instituteName: 'Mugda Medical College', type: 'Public' },
  { instituteName: 'Habiganj Medical College', type: 'Public' },
  { instituteName: 'Netrokona Medical College, Netrokona', type: 'Public' },
  { instituteName: 'Nilphamari Medical College', type: 'Public' },
  { instituteName: 'Magura Medical College', type: 'Public' },
  { instituteName: 'Naogaon Medical College', type: 'Public' },
  { instituteName: 'Chandpur Medical College', type: 'Public' },
  { instituteName: 'Sunamganj Medical College', type: 'Public' },

  // Private Medical Colleges
  { instituteName: 'Dhaka National Medical College', type: 'Private' },
  { instituteName: 'Ibrahim Medical College', type: 'Private' },
  { instituteName: 'Bangladesh Medical College', type: 'Private' },
  {
    instituteName: 'Holy Family Red Crescent Medical College',
    type: 'Private',
  },
  { instituteName: 'Jahurul Islam Medical College', type: 'Private' },
  { instituteName: 'Uttara Adhunik Medical College', type: 'Private' },
  { instituteName: 'Shaheed Monsur Ali Medical College', type: 'Private' },
  { instituteName: 'Enam Medical College and Hospital', type: 'Private' },
  { instituteName: 'Community Based Medical College', type: 'Private' },
  {
    instituteName: 'Universal Medical College and Hospital, Dhaka',
    type: 'Private',
  },
  { instituteName: 'Ibn Sina Medical College', type: 'Private' },
  { instituteName: 'TMSS Medical College', type: 'Private' },
  { instituteName: 'Shahabuddin Medical College', type: 'Private' },
  { instituteName: 'Medical College for Women & Hospital', type: 'Private' },
  { instituteName: "Z. H. Sikder Women's Medical College", type: 'Private' },
  { instituteName: "Kumudini Women's Medical College", type: 'Private' },
  { instituteName: 'Tairunnessa Memorial Medical College', type: 'Private' },
  { instituteName: "Ad-din Women's Medical College", type: 'Private' },
  { instituteName: 'International Medical College', type: 'Private' },
  { instituteName: 'Central Medical College', type: 'Private' },
  { instituteName: 'BGC Trust Medical College', type: 'Private' },
  { instituteName: 'Eastern Medical College', type: 'Private' },
  { instituteName: 'Islami Bank Medical College', type: 'Private' },
  { instituteName: 'Khwaja Yunus Ali Medical College', type: 'Private' },
  { instituteName: 'Jalalabad Ragib-Rabeya Medical College', type: 'Private' },
  { instituteName: 'East West Medical College', type: 'Private' },
  { instituteName: 'North East Medical College', type: 'Private' },
  {
    instituteName: 'Chattagram Maa-O-Shishu Hospital Medical College',
    type: 'Private',
  },
  {
    instituteName: 'Gonoshasthaya Samaj Vittik Medical College',
    type: 'Private',
  },
  { instituteName: 'Institute of Applied Health Sciences', type: 'Private' },
  { instituteName: 'North Bengal Medical College', type: 'Private' },
  { instituteName: 'Prime Medical College', type: 'Private' },
  { instituteName: 'Rangpur Community Medical College', type: 'Private' },
  { instituteName: 'Delta Medical College', type: 'Private' },
  { instituteName: 'Southern Medical College', type: 'Private' },
  { instituteName: 'Anwer Khan Modern Medical College', type: 'Private' },
  { instituteName: 'Ad-din Sakina Medical College', type: 'Private' },
  { instituteName: 'Popular Medical College', type: 'Private' },
  { instituteName: 'Green Life Medical College', type: 'Private' },
  { instituteName: 'Dhaka Community Medical College', type: 'Private' },
  { instituteName: "Sylhet Women's Medical College", type: 'Private' },
  { instituteName: 'Monno Medical College', type: 'Private' },
  { instituteName: 'MH Samorita Medical College', type: 'Private' },
  { instituteName: 'City Medical College', type: 'Private' },
  { instituteName: 'Marks Medical College', type: 'Private' },
  { instituteName: 'Diabetic Association Medical College', type: 'Private' },
  { instituteName: 'Barind Medical College', type: 'Private' },
  { instituteName: 'Gazi Medical College', type: 'Private' },
  { instituteName: 'Northern International Medical College', type: 'Private' },
  { instituteName: 'Dr. Sirajul Islam Medical College', type: 'Private' },
  { instituteName: 'Mainamoti Medical College', type: 'Private' },
  { instituteName: "Bikrampur Bhuiyan's Medical College", type: 'Private' },
  {
    instituteName: 'Dhaka Central International Medical College',
    type: 'Private',
  },
  { instituteName: 'Ashiyan Medical College', type: 'Private' },
  { instituteName: 'US-Bangla Medical College', type: 'Private' },
  { instituteName: 'President Abdul Hamid Medical College', type: 'Private' },
  { instituteName: 'Brahmanbaria Medical College', type: 'Private' },
  { instituteName: 'Parkview Medical College', type: 'Private' },
  { instituteName: 'Ad-Din Akij Medical College', type: 'Private' },
  { instituteName: 'Monowara Sikder Medical College', type: 'Private' },
  { instituteName: 'Bashundhara Ad-din Medical College', type: 'Private' },
  { instituteName: 'Aichi Medical College', type: 'Private' },
  { instituteName: 'Marine City Medical College', type: 'Private' },
  { instituteName: 'Khulna City Medical College', type: 'Private' },
  {
    instituteName: 'Chattagram International Medical College',
    type: 'Private',
  },
  { instituteName: 'United Medical College', type: 'Private' },
  { instituteName: 'South Apollo Medical College', type: 'Private' },
  { instituteName: 'Ahsania Mission Medical College', type: 'Private' },
  { instituteName: 'Asgar Ali Medical College', type: 'Private' },

  // Military Medical Colleges
  { instituteName: 'Armed Forces Medical College', type: 'Military' },
  { instituteName: 'Army Medical College Bogura', type: 'Military' },
  { instituteName: 'Army Medical College, Chittagong', type: 'Military' },
  { instituteName: 'Army Medical College Cumilla', type: 'Military' },
  { instituteName: 'Army Medical College, Jashore', type: 'Military' },
  { instituteName: 'Rangpur Army Medical College', type: 'Military' },
  {
    instituteName: 'Bangladesh Navy Medical College, Chittogram',
    type: 'Military',
  },

  // Public Medical Universities
  { instituteName: 'Bangladesh Medical University', type: 'Public University' },
  { instituteName: 'Chittagong Medical University', type: 'Public University' },
  { instituteName: 'Rajshahi Medical University', type: 'Public University' },
  { instituteName: 'Sylhet Medical University', type: 'Public University' },
  { instituteName: 'Khulna Medical University', type: 'Public University' },
];
